general.import = ["~/.config/alacritty/theme.toml"]

[env]
TERM = "xterm-256color"

[font]

normal = { family = "JetBrains Mono" }
bold = { family = "JetBrains Mono" }
italic = { family = "JetBrains Mono" }
size = 10.5
offset = { x = 0, y = 6 }

[window]
padding.x = 0
padding.y = 0
decorations = "None"
dynamic_padding = true

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
