source ~/.local/share/omarchy/default/bash/rc
source ~/Projects/dotfiles/shell/common/history-refresh
source ~/Projects/dotfiles/shell/common/aliases
source ~/Projects/dotfiles/shell/common/envs
source ~/Projects/dotfiles/shell/common/tmux
source ~/Projects/dotfiles/shell/bash/init
