source ~/Projects/dotfiles/shell/zsh/init
source ~/Projects/dotfiles/shell/common/history-refresh
source ~/Projects/dotfiles/shell/common/aliases
source ~/Projects/dotfiles/shell/common/functions
source ~/Projects/dotfiles/shell/zsh/completions
source ~/Projects/dotfiles/macos/nvm
source ~/Projects/dotfiles/shell/common/envs
[[ $- == *i* ]] && source ~/Projects/dotfiles/shell/zsh/inputrc
source ~/Projects/dotfiles/shell/common/tmux
