source ~/.dotfiles/shell/zsh/brew
source ~/.dotfiles/shell/zsh/init
source ~/.dotfiles/shell/common/aliases
source ~/.dotfiles/shell/common/functions
source ~/.dotfiles/shell/common/docker
source ~/.dotfiles/shell/zsh/completions
source ~/.dotfiles/shell/platform/macos/nvm
source ~/.dotfiles/shell/common/envs
source ~/.dotfiles/shell/zsh/mise
source ~/.dotfiles/shell/zsh/zoxide
[[ $- == *i* ]] && source ~/.dotfiles/shell/zsh/inputrc
source ~/.dotfiles/shell/common/tmux
