[settings]
trusted_config_paths = ['~/projects']

[tools]
bun = "latest"
claude = "latest"
codex = "latest"
cspell = "latest"
gemini = { version = "latest", allow_builds = ["@github/keytar", "node-pty"] }
gh = "latest"
go = "latest"
node = { version = "latest", os = ["linux"] }
"npm:@vlabo/cspell-lsp" = "latest"
opencode = "latest"
python = "latest"
